### PR TITLE
Session data now can be in `bytes` in python3

### PR DESCRIPTION
**Pull request by Lukkra211**
We sometimes have `bytes` string in the data. In python2, this isn't a problem since the json library decodes the string. In python3, calling the requests would raise an error.

Since the library behaves differently based on the python version, I decided to fix this by converting the string in python3 as well.

### CODE REVIEW

**Comment by Allda** [comment]
What's a reason of replacing requests `json` argument with `data`?

**Comment by Lukkra211** [comment]
> What's a reason of replacing requests `json` argument with `data`?
(Please see the description I've added). If I would use the `json` argument, I wouldn't be able to change the JSONEncoder, which raises the error when processing `bytes`. So I encoded it beforehand with a custom encoder instead.

**Comment by Lukkra211** [comment]
@Allda ^

**Comment by jvulgan** [comment]
I think the change looks good but needs better commit message cause at the moment it's not obvious, why you have to encode it yourself. At least add the info you provided in the comments above, about it raising exception and that's why you don't use `json` but instead use `data` with custom encoder.

Also the commit that bumps the version to `1.0.2` doesn't seem like it belongs here?

**Comment by Lukkra211** [comment]
@jvulgan All should be fixed now.

**Comment by Lukkra211** [comment]
Closing, after a conversation with @kusha.

**Pull request closed without merging**
